pageinfo = [[0,0,0,0,null],
	[0,0,0,5,null],
	[0,0,0,5,null],
	[0,0,0,5,null],
	[0,0,0,5,null],
	[0,0,0,5,null],
	[0,0,0,5,null],
	[0,0,0,5,null],
	[0,0,0,5,null],
	[0,0,0,5,null],
	[0,0,0,5,null],
	[0,0,0,5,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./bestpractices.htm","Technical Procedures and Best Practices","A guide to effective procedures",""],
["./documents/Agency_Partner_DeployProcess.pdf","Agency_Partner_DeployProcess.pdf","Deployment Process FOR AGENCY PARTNERS Deployment Process for Agency Partners This document describes the processes and best practices used by age...",""],
["./documents/campaigntracking.pdf","campaigntracking.pdf","Campaign Tracking - Rollins The following documentation will outline the steps necessary to track Rollins campaigns. Campaign Tracking ‚&#128;&#162; There a...",""],
["./documents/CollabNet_scrumreferencecard.pdf","CollabNet_scrumreferencecard.pdf","Scrum Reference Card by Michael James, CollabNet Inc. About Scrum Scrum Roles A Management Framework Product Owner Scrum is a management framework...",""],
["./documents/CredentialsStorageProposal.pdf","CredentialsStorageProposal.pdf","Proposed Marketing Credentials Management The Rollins Marketing team would benefit from a secure, central storage area for credentials. These cred...",""],
["./documents/CrisisManagementSummary.pdf","CrisisManagementSummary.pdf","Orkin.com Outage 10/24/2016 CRISIS MANAGEMENT SUMMARY Executive Summary ‚&#128;&#162; On the afternoon of Monday, October 24, 2016, a website monitoring ser...",""],
["./documents/currentcalendar.pdf","currentcalendar.pdf","TECHNOLOGY DEPLOYMENT SCHEDULE January 2017 Sprint 24 SUNDAY MONDAY TUESDAY WEDNESDAY THURSDAY FRIDAY SATURDAY 1 2 3 4 5 6 7 AGENCY + SEO + ST: RO...",""],
["./documents/InternationalFranchise_Packet.pdf","InternationalFranchise_Packet.pdf","Orkin Pest Control Franchise Use the following checklist to ensure prompt creation of your website. ÔÅ&#39; Responsible Task Time Frame Information Pa...",""],
["./documents/LanguagesWordPress.pdf","LanguagesWordPress.pdf","Step 1: Login to orkin.com. On top change from English to Spanish. Step 2: just dump all the pages from Spanish site ‚&#128;úes.orkin.com‚&#128;ù to here un...",""],
["./documents/Rollins_Contributor_DeployProcess.pdf","Rollins_Contributor_DeployProcess.pdf","Deployment Process FOR ROLLINS CONTRIBUTORS Deployment Process for Rollins Contributors This document describes the processes and best practices u...",""],
["./documents/WordPressGuide.pdf","WordPressGuide.pdf","Wordpress documentation Login to the wordpress Dashboard: ÔÇ Once you have your username and password, use the following URL to log-in when needed...",""],
["./documents/WPFolderStructure.pdf","WPFolderStructure.pdf","1) Basic Folder Structure. Wp-config file must be in the root folder. 2) All the word press theme files, plugin and version files are under wp-con...",""],
["./downloads.htm","Download a Document","Download PDF documents",""],
["./FAQ.htm","Frequently Asked Questions","Questions we&#39;ve noticed are asked on a frequent basis",""],
["./GitHub.htm","GitHub Repositories","A guide to working with Rollins GitHub repositories",""],
["./Glossaries.htm","Glossaries","A collection of helpful glossaries",""],
["./GlossaryRollins.htm","Rollins Glossary","A glossary of common Rollins terms",""],
["./header.htm","Marketing Help","",""],
["./international.htm","Creating International Franchise Sites","A guide to creating and maintaining International Franchise websites",""],
["./mcc.htm","Using the Marketing Command Center","A guide to the tools and features of the Marketing Command Center",""],
["./mtech/header.htm","Marketing Help","",""],
["./phonekeyword.htm","Call Conversion Tracking","A look at the backend process that enables phone lead tracking",""],
["./risk.htm","Troubleshooting and Risk","Eliminating, avoiding, and solving common problems",""],
["./settings.php","No title","",""],
["./Sprint_Deploy.htm","Sprint Cycle and Deployment","Exploring the Rollins software development life cycle",""],
["./sys_monitoring.htm","System Monitoring","A look at the tools Rollins uses to monitor websites and other systems",""],
["./VersionOne.htm","Using VersionOne","Using VersionOne to track requests, tasks, and defects against the sprint cycle",""]];
